"""empty message

Revision ID: 0457fb4f0f1f
Revises: 42ed4faa1e42
Create Date: 2026-02-15 17:27:24.014243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0457fb4f0f1f'
down_revision: Union[str, Sequence[str], None] = '42ed4faa1e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodical_magazine', sa.Column('reference_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodical_magazine', 'reference_period')
    # ### end Alembic commands ###
