"""empty message

Revision ID: 20ee809d2d71
Revises: e425cef08ece
Create Date: 2026-02-16 14:21:25.058073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ee809d2d71'
down_revision: Union[str, Sequence[str], None] = 'e425cef08ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_address',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('organ', sa.String(), nullable=True),
    sa.Column('unity', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('public_place', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('mailbox', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('url_homepage', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher_address')
    # ### end Alembic commands ###
