"""empty message

Revision ID: 2a83e4d180b6
Revises: 3e5a6c566f50
Create Date: 2026-02-19 16:51:12.520229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a83e4d180b6'
down_revision: Union[str, Sequence[str], None] = '3e5a6c566f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openalex_researcher',
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('scopus', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=255), nullable=True),
    sa.Column('openalex', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openalex_researcher')
    # ### end Alembic commands ###
