"""empty message

Revision ID: 2aa0a7e2f7bc
Revises: 6cf1cf66e64c
Create Date: 2026-03-04 06:11:27.978542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa0a7e2f7bc'
down_revision: Union[str, Sequence[str], None] = '6cf1cf66e64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_or_tv_program',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_or_tv_program')
    # ### end Alembic commands ###
