"""empty message

Revision ID: 2eabd1fb6db4
Revises: 55de0fea2906
Create Date: 2026-02-16 10:02:32.867377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eabd1fb6db4'
down_revision: Union[str, Sequence[str], None] = '55de0fea2906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('lattes_10_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('citations', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('abstract_ai', sa.Text(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('classification', postgresql.ENUM('A_PLUS', 'A', 'B_PLUS', 'B', 'C_PLUS', 'C', 'D_PLUS', 'D', 'E_PLUS', 'E', name='classification_class'), server_default=sa.text("'E'"), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('qtt_publications', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('graduate_program', sa.String(), nullable=True),
    sa.Column('graduation', sa.String(), nullable=True),
    sa.Column('update_abstract', sa.Boolean(), nullable=True),
    sa.Column('docente', sa.Boolean(), nullable=False),
    sa.Column('student', sa.Boolean(), nullable=False),
    sa.Column('extra_field', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lattes_10_id'),
    sa.UniqueConstraint('lattes_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher')
    # ### end Alembic commands ###
