"""empty message

Revision ID: 348751a4adb9
Revises: b0b0223646b9
Create Date: 2026-02-18 13:16:13.837898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348751a4adb9'
down_revision: Union[str, Sequence[str], None] = 'b0b0223646b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researcher', sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researcher', 'has_image')
    # ### end Alembic commands ###
