"""empty message

Revision ID: 3e30166ea95e
Revises: 20ee809d2d71
Create Date: 2026-02-16 14:23:50.859382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e30166ea95e'
down_revision: Union[str, Sequence[str], None] = '20ee809d2d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('area_specialty_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.ForeignKeyConstraint(['area_specialty_id'], ['area_specialty.id'], ),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher_area_expertise')
    # ### end Alembic commands ###
