"""empty message

Revision ID: 3e5a6c566f50
Revises: b893a15b9b00
Create Date: 2026-02-19 09:35:34.462494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5a6c566f50'
down_revision: Union[str, Sequence[str], None] = 'b893a15b9b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS unaccent;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP EXTENSION IF EXISTS unaccent;')
    pass
    # ### end Alembic commands ###
