"""empty message

Revision ID: 42ed4faa1e42
Revises: f13d85bf134a
Create Date: 2026-02-15 17:22:53.088190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ed4faa1e42'
down_revision: Union[str, Sequence[str], None] = 'f13d85bf134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodical_magazine',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodical_magazine')
    # ### end Alembic commands ###
