"""empty message

Revision ID: 55de0fea2906
Revises: 75c08b8d22ad
Create Date: 2026-02-16 09:05:00.834098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55de0fea2906'
down_revision: Union[str, Sequence[str], None] = '75c08b8d22ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('great_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_specialty',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_specialty')
    op.drop_table('sub_area_expertise')
    op.drop_table('area_expertise')
    op.drop_table('great_area_expertise')
    # ### end Alembic commands ###
