"""empty message

Revision ID: 67fa79b921cb
Revises: d056595803ab
Create Date: 2026-02-16 16:09:47.154154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fa79b921cb'
down_revision: Union[str, Sequence[str], None] = 'd056595803ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibliographic_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('means_divulgation', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scientific_divulgation', sa.Boolean(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year_', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_article',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('periodical_magazine_id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('fascicle', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('place_publication', sa.String(), nullable=True),
    sa.Column('periodical_magazine_name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.ForeignKeyConstraint(['periodical_magazine_id'], ['periodical_magazine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('qtt_pages', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book_chapter',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('organizers', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bibliographic_production_book_chapter')
    op.drop_table('bibliographic_production_book')
    op.drop_table('bibliographic_production_article')
    op.drop_table('bibliographic_production')
    # ### end Alembic commands ###
