"""empty message

Revision ID: 827de77edd1e
Revises: 441b1bb149aa
Create Date: 2026-03-03 22:36:09.573449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827de77edd1e'
down_revision: Union[str, Sequence[str], None] = '441b1bb149aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'software', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'software', type_='unique')
    op.drop_column('software', 'code')
    # ### end Alembic commands ###
