"""empty message

Revision ID: 82af0aaac3bb
Revises: 3e30166ea95e
Create Date: 2026-02-16 14:27:30.340892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82af0aaac3bb'
down_revision: Union[str, Sequence[str], None] = '3e30166ea95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('education_name', sa.String(), nullable=True),
    sa.Column('education_start', sa.Integer(), nullable=True),
    sa.Column('education_end', sa.Integer(), nullable=True),
    sa.Column('key_words', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
