"""empty message

Revision ID: a7c0bf36b9a9
Revises: 348751a4adb9
Create Date: 2026-02-18 18:30:01.825366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c0bf36b9a9'
down_revision: Union[str, Sequence[str], None] = '348751a4adb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('oriented', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('research_project_foment', 'agency_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('research_project_production', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_project_production', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('research_project_foment', 'agency_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('guidance')
    # ### end Alembic commands ###
