"""empty message

Revision ID: a982d3f55527
Revises: a95b223dda79
Create Date: 2026-03-04 01:16:44.348943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a982d3f55527'
down_revision: Union[str, Sequence[str], None] = 'a95b223dda79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_cultivar', sa.Column('researcher_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'registered_cultivar', 'researcher', ['researcher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registered_cultivar', type_='foreignkey')
    op.drop_column('registered_cultivar', 'researcher_id')
    # ### end Alembic commands ###
