"""empty message

Revision ID: b0b0223646b9
Revises: 
Create Date: 2026-02-17 10:37:11.525055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b0223646b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=False),
    sa.Column('alpha_2_code', sa.String(length=2), nullable=True),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_2_code'),
    sa.UniqueConstraint('alpha_3_code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_pt')
    )
    op.create_table('great_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jcr',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('journalname', sa.String(), nullable=True),
    sa.Column('jcryear', sa.String(), nullable=True),
    sa.Column('abbrjournal', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('eissn', sa.String(), nullable=True),
    sa.Column('totalcites', sa.String(), nullable=True),
    sa.Column('totalarticles', sa.String(), nullable=True),
    sa.Column('citableitems', sa.String(), nullable=True),
    sa.Column('citedhalflife', sa.String(), nullable=True),
    sa.Column('citinghalflife', sa.String(), nullable=True),
    sa.Column('jif2019', sa.Float(), nullable=True),
    sa.Column('url_revista', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodical_magazine',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('reference_period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('first_leader', sa.String(), nullable=True),
    sa.Column('first_leader_id', sa.UUID(), nullable=True),
    sa.Column('second_leader', sa.String(), nullable=True),
    sa.Column('second_leader_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('census', sa.Integer(), nullable=True),
    sa.Column('start_of_collection', sa.String(), nullable=True),
    sa.Column('end_of_collection', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_identifier'),
    sa.UniqueConstraint('name', 'institution', name='uq_research_group_name_institution')
    )
    op.create_table('area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('research_group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('predominant_major_area', sa.String(), nullable=True),
    sa.Column('predominant_area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_specialty',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('lattes_10_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('citations', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('abstract_ai', sa.Text(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('qtt_publications', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('graduate_program', sa.String(), nullable=True),
    sa.Column('graduation', sa.String(), nullable=True),
    sa.Column('update_abstract', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lattes_10_id'),
    sa.UniqueConstraint('lattes_id')
    )
    op.create_table('advisory_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('organ_name', sa.String(), nullable=False),
    sa.Column('start_year', sa.String(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('organ_code', sa.String(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('is_current', sa.String(), nullable=True),
    sa.Column('start_month', sa.String(), nullable=True),
    sa.Column('end_month', sa.String(), nullable=True),
    sa.Column('end_year', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artistic_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('means_divulgation', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scientific_divulgation', sa.Boolean(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('year_', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('didactic_material',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('education_name', sa.String(), nullable=True),
    sa.Column('education_start', sa.Integer(), nullable=True),
    sa.Column('education_end', sa.Integer(), nullable=True),
    sa.Column('key_words', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('promoter_institution', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('duration_in_weeks', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industrial_design',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_map_or_similar',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_artistic_work',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mockup',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_technical_production',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('development_year', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('deposit_date', sa.String(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('process_or_technique',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('home_page', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_innovation_potential', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('purpose_en', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('funding_institution', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishing',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_project',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('number_undergraduates', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_specialists', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_academic_masters', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('number_phd', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_report',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_address',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('organ', sa.String(), nullable=True),
    sa.Column('unity', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('public_place', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('mailbox', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('url_homepage', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.Column('area_specialty_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.ForeignKeyConstraint(['area_specialty_id'], ['area_specialty.id'], ),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_course',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_website_blog',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('production_sequence', sa.Integer(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('dissemination_medium', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('funding_institution', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work_presentation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('promoting_institution', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_work_program',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technological_product',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_article',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('periodical_magazine_id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('fascicle', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('place_publication', sa.String(), nullable=True),
    sa.Column('periodical_magazine_name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.ForeignKeyConstraint(['periodical_magazine_id'], ['periodical_magazine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('qtt_pages', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_book_chapter',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('qtt_volume', sa.String(), nullable=True),
    sa.Column('organizers', sa.String(), nullable=True),
    sa.Column('num_edition_revision', sa.String(), nullable=True),
    sa.Column('num_series', sa.String(), nullable=True),
    sa.Column('publishing_company', sa.String(), nullable=True),
    sa.Column('publishing_company_city', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bibliographic_production_work_in_event',
    sa.Column('bibliographic_production_id', sa.UUID(), nullable=False),
    sa.Column('event_classification', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_city', sa.String(), nullable=True),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.Column('proceedings_title', sa.String(), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('start_page', sa.String(), nullable=True),
    sa.Column('end_page', sa.String(), nullable=True),
    sa.Column('publisher_name', sa.String(), nullable=True),
    sa.Column('publisher_city', sa.String(), nullable=True),
    sa.Column('event_name_english', sa.String(), nullable=True),
    sa.Column('identifier_number', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['bibliographic_production_id'], ['bibliographic_production.id'], ),
    sa.PrimaryKeyConstraint('bibliographic_production_id')
    )
    op.create_table('research_project_components',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('citations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_project_foment',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'agency_name')
    )
    op.create_table('research_project_production',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_project_production')
    op.drop_table('research_project_foment')
    op.drop_table('research_project_components')
    op.drop_table('bibliographic_production_work_in_event')
    op.drop_table('bibliographic_production_book_chapter')
    op.drop_table('bibliographic_production_book')
    op.drop_table('bibliographic_production_article')
    op.drop_table('technological_product')
    op.drop_table('technical_work_program')
    op.drop_table('technical_work_presentation')
    op.drop_table('technical_work')
    op.drop_table('software')
    op.drop_table('social_media_website_blog')
    op.drop_table('short_course')
    op.drop_table('researcher_area_expertise')
    op.drop_table('researcher_address')
    op.drop_table('research_report')
    op.drop_table('research_project')
    op.drop_table('publishing')
    op.drop_table('process_or_technique')
    op.drop_table('patent')
    op.drop_table('other_technical_production')
    op.drop_table('mockup')
    op.drop_table('maintenance_artistic_work')
    op.drop_table('letter_map_or_similar')
    op.drop_table('industrial_design')
    op.drop_table('event_organization')
    op.drop_table('education')
    op.drop_table('didactic_material')
    op.drop_table('brand')
    op.drop_table('bibliographic_production')
    op.drop_table('artistic_production')
    op.drop_table('advisory_activity')
    op.drop_table('researcher')
    op.drop_table('area_specialty')
    op.drop_table('sub_area_expertise')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('research_lines')
    op.drop_table('area_expertise')
    op.drop_table('research_group')
    op.drop_table('periodical_magazine')
    op.drop_table('jcr')
    op.drop_table('institution')
    op.drop_table('great_area_expertise')
    op.drop_table('country')
    # ### end Alembic commands ###
