"""empty message

Revision ID: b893a15b9b00
Revises: 237662e4c56c
Create Date: 2026-02-18 23:37:50.465040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b893a15b9b00'
down_revision: Union[str, Sequence[str], None] = '237662e4c56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foment',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('modality_code', sa.String(), nullable=True),
    sa.Column('modality_name', sa.String(), nullable=True),
    sa.Column('call_title', sa.String(), nullable=True),
    sa.Column('category_level_code', sa.String(), nullable=True),
    sa.Column('funding_program_name', sa.String(), nullable=True),
    sa.Column('institute_name', sa.String(), nullable=True),
    sa.Column('aid_quantity', sa.Integer(), nullable=True),
    sa.Column('scholarship_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foment')
    # ### end Alembic commands ###
