"""empty message

Revision ID: bf1c9aad1865
Revises: 
Create Date: 2026-02-16 14:04:26.874356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1c9aad1865'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('country',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=False),
    sa.Column('alpha_2_code', sa.String(length=2), nullable=True),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_2_code'),
    sa.UniqueConstraint('alpha_3_code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_pt')
    )
    op.create_table('great_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jcr',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('journalname', sa.String(), nullable=True),
    sa.Column('jcryear', sa.String(), nullable=True),
    sa.Column('abbrjournal', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('eissn', sa.String(), nullable=True),
    sa.Column('totalcites', sa.String(), nullable=True),
    sa.Column('totalarticles', sa.String(), nullable=True),
    sa.Column('citableitems', sa.String(), nullable=True),
    sa.Column('citedhalflife', sa.String(), nullable=True),
    sa.Column('citinghalflife', sa.String(), nullable=True),
    sa.Column('jif2019', sa.Float(), nullable=True),
    sa.Column('url_revista', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodical_magazine',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('qualis', sa.String(), nullable=True),
    sa.Column('jcr', sa.String(), nullable=True),
    sa.Column('jcr_link', sa.String(), nullable=True),
    sa.Column('reference_period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('first_leader', sa.String(), nullable=True),
    sa.Column('first_leader_id', sa.UUID(), nullable=True),
    sa.Column('second_leader', sa.String(), nullable=True),
    sa.Column('second_leader_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('census', sa.Integer(), nullable=True),
    sa.Column('start_of_collection', sa.String(), nullable=True),
    sa.Column('end_of_collection', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_identifier'),
    sa.UniqueConstraint('name', 'institution', name='uq_research_group_name_institution')
    )
    op.create_table('area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('great_area_expertise_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['great_area_expertise_id'], ['great_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('research_group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('predominant_major_area', sa.String(), nullable=True),
    sa.Column('predominant_area', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_group_id'], ['research_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_area_expertise',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_expertise_id'], ['area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_specialty',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sub_area_expertise_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_expertise_id'], ['sub_area_expertise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
    op.drop_table('area_specialty')
    op.drop_table('sub_area_expertise')
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('research_lines')
    op.drop_table('area_expertise')
    op.drop_table('research_group')
    op.drop_table('periodical_magazine')
    op.drop_table('jcr')
    op.drop_table('institution')
    op.drop_table('great_area_expertise')
    op.drop_table('country')
    # ### end Alembic commands ###
