"""empty message

Revision ID: c2c457c047fa
Revises: 67fa79b921cb
Create Date: 2026-02-16 16:30:29.649479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c457c047fa'
down_revision: Union[str, Sequence[str], None] = '67fa79b921cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('nature', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('development_year', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('deposit_date', sa.String(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('research_report',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('relevance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('financing_institutionc', sa.String(), nullable=True),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('stars', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software')
    op.drop_table('research_report')
    op.drop_table('patent')
    op.drop_table('brand')
    # ### end Alembic commands ###
