"""empty message

Revision ID: d056595803ab
Revises: 82af0aaac3bb
Create Date: 2026-02-16 14:59:38.744683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd056595803ab'
down_revision: Union[str, Sequence[str], None] = '82af0aaac3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'status')
    # ### end Alembic commands ###
