"""empty message

Revision ID: e2762132f61b
Revises: 2aa0a7e2f7bc
Create Date: 2026-03-04 08:15:30.742256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2762132f61b'
down_revision: Union[str, Sequence[str], None] = '2aa0a7e2f7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_project_components', sa.Column('coordinator', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_project_components', 'coordinator')
    # ### end Alembic commands ###
