"""empty message

Revision ID: e425cef08ece
Revises: bf1c9aad1865
Create Date: 2026-02-16 14:14:45.985244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e425cef08ece'
down_revision: Union[str, Sequence[str], None] = 'bf1c9aad1865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lattes_id', sa.String(), nullable=True),
    sa.Column('lattes_10_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('citations', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_en', sa.Text(), nullable=True),
    sa.Column('abstract_ai', sa.Text(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('qtt_publications', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('graduate_program', sa.String(), nullable=True),
    sa.Column('graduation', sa.String(), nullable=True),
    sa.Column('update_abstract', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lattes_10_id'),
    sa.UniqueConstraint('lattes_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researcher')
    # ### end Alembic commands ###
