"""empty message

Revision ID: ee325917af55
Revises: 0457fb4f0f1f
Create Date: 2026-02-15 17:50:46.443662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee325917af55'
down_revision: Union[str, Sequence[str], None] = '0457fb4f0f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('first_leader', sa.String(), nullable=True),
    sa.Column('first_leader_id', sa.UUID(), nullable=True),
    sa.Column('second_leader', sa.String(), nullable=True),
    sa.Column('second_leader_id', sa.UUID(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('census', sa.Integer(), nullable=True),
    sa.Column('start_of_collection', sa.String(), nullable=True),
    sa.Column('end_of_collection', sa.String(), nullable=True),
    sa.Column('group_identifier', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_identifier'),
    sa.UniqueConstraint('name', 'institution', name='uq_research_group_name_institution')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_group')
    # ### end Alembic commands ###
