"""empty message

Revision ID: f13d85bf134a
Revises: 
Create Date: 2026-02-15 16:35:58.094997

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f13d85bf134a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=False),
    sa.Column('alpha_2_code', sa.String(length=2), nullable=True),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alpha_2_code'),
    sa.UniqueConstraint('alpha_3_code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_pt')
    )
    op.create_table('jcr',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('journalname', sa.String(), nullable=True),
    sa.Column('jcryear', sa.String(), nullable=True),
    sa.Column('abbrjournal', sa.String(), nullable=True),
    sa.Column('issn', sa.String(), nullable=True),
    sa.Column('eissn', sa.String(), nullable=True),
    sa.Column('totalcites', sa.String(), nullable=True),
    sa.Column('totalarticles', sa.String(), nullable=True),
    sa.Column('citableitems', sa.String(), nullable=True),
    sa.Column('citedhalflife', sa.String(), nullable=True),
    sa.Column('citinghalflife', sa.String(), nullable=True),
    sa.Column('jif2019', sa.Float(), nullable=True),
    sa.Column('url_revista', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP EXTENSION "uuid-ossp"')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('state')
    op.drop_table('jcr')
    op.drop_table('country')
    # ### end Alembic commands ###
